// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyptaqljdkvrviegrfct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5cHRhcWxqZGt2cnZpZWdyZmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTY2NjQsImV4cCI6MjA2MDQ3MjY2NH0.uJSAl1d3GOGaL86zKpnUsczlv8CuUHEbJH03nALb9Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);