// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vanxomunmbtronfwlqwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbnhvbXVubWJ0cm9uZndscXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDM4MDMsImV4cCI6MjA2MTA3OTgwM30.rMDkt11yZA5G27EHPmE4JsR-cJjPgCksLxuVyhCw1Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);